name: End-to-end tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install Java 8
          uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '8'

        - name: Install yarn
          run: npm install -g yarn

        - name: Install deps
          run: npm install

        - name: Clone web app
          run: git clone https://github.com/cypress-io/cypress-realworld-app.git

        - name: Install deps for web app
          run: cd cypress-realworld-app && yarn install

        - name: Start local server
          run: cd cypress-realworld-app && yarn dev & sleep 20 && curl http://localhost:3000

        - name: Run tests
          run: npx cross-env ENV=http://localhost:3000/ wdio run ./headless.wdio.conf.js && npx allure generate allure-results-chrome -o allure-report --clean || npx allure generate allure-results-chrome -o allure-report --clean

        - name: Deploy report to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-report
