name: End-to-end tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Java 8
          run: choco install openjdk8
        - name: Install yarn
          run: npm install -g yarn
        - name: Install deps
          run: npm install
        - name: Clone web app
          run: git clone https://github.com/cypress-io/cypress-realworld-app.git
        - name: Install deps for web app
          run: cd cypress-realworld-app && yarn install
        - name: Start local server
          run: |
              cd cypress-realworld-app
              yarn dev > /dev/null 2>&1 &
              while ! curl -s http://localhost:3001; do sleep 5; done
        - name: Run tests
          run: npm run wdio:chrome
        - name: Deploy report to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-report
